name: Build and Publish
run-name: ${{ github.actor }} is building 🚀
on:
  push:
    branches:
      - main       # Run the worfklow on push events to main
  pull_request:
    branches:
      - '*'        # Run the workflow for all pull requests
  release:
    types:
      - published  # Run the workflow when a release is published

defaults:
  run:
    shell: pwsh

env:
  BuildDirectory: ${{ github.workspace }}/.build

jobs:
  build:
    name: Run build.ps1 build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      # Run the build script to create the versioned script file
      - name: Build
        run: |
          ./build.ps1
        shell: pwsh

      # Publish the script as an artifact, so it can be used in other jobs
      - uses: actions/upload-artifact@v3
        with:
          name: Artifact
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.BuildDirectory }}/*

  deploy:
    # Publish only when creating a GitHub Release
    # https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4

      # Download the script created in the previous job
      - uses: actions/download-artifact@v3
        with:
          name: Artifact
          path: ${{ env.BuildDirectory }}

      # Publish package
      - name: Publish script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.ps1 publish
