name: Slash Command Dispatch
run-name: ${{ github.actor }} issued a command 🚀
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Dispatching slash command'

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: |
            publish
